<?php

/**
 * @file
 * File description.
 *
 * Long description.
 */

use Drupal\Core\File\FileExists;
use Drupal\Core\File\FileSystemInterface;
use Drupal\file\Entity\File;
use Drupal\media\Entity\Media;

/**
 * Install/Update function for setting the default image on the photo field.
 */
function _stanford_person_install_default_photo() {
  // Services.
  $file_system = \Drupal::service('file_system');
  $erepo = \Drupal::service('entity.repository');

  // File UUID.
  $fuuid = '4d5dde7e-f2c7-4d27-8ad1-99623b1308f8';
  // Media UUID.
  $muuid = 'a4660e7f-d4bf-4a28-8030-9dc8576b1c9a';

  // Move the physical file in to place.
  $saved = _stanford_person_install_default_photo_file();

  // Try to get the image first.
  $image = $erepo->loadEntityByUuid('file', $fuuid);

  // Save the file/media entities and ensure their UUIDs.
  if (!$image) {
    $image = File::create();
    $image->setFileUri($saved);
    $image->set('uuid', $fuuid);
    $image->setOwnerId(\Drupal::currentUser()->id());
    $image->setMimeType('image/' . pathinfo($saved, PATHINFO_EXTENSION));
    $image->setFileName($file_system->basename($saved));
    $image->setPermanent();
    $image->save();
  }

  // Try to get the media item first.
  $image_media = $erepo->loadEntityByUuid('media', $muuid);

  // Create one if not exist.
  if (!$image_media) {
    // Create media entity with saved file.
    $image_media = Media::create([
      'bundle' => 'image',
      'uuid' => $muuid,
      'uid' => \Drupal::currentUser()->id(),
      'langcode' => \Drupal::languageManager()->getDefaultLanguage()->getId(),
      'field_media_image' => [
        'target_id' => $image->id(),
        'alt' => '',
        'title' => '',
      ],
    ]);
    $image_media->save();
  }

}

/**
 * Move the file into the file system.
 *
 * @return string
 *   The file uri.
 */
function _stanford_person_install_default_photo_file() {
  // Services.
  $file_system = \Drupal::service('file_system');

  // Save the file to public.
  $destination = 'public://media/image';
  $source = $file_system->realpath(
    \Drupal::service('extension.list.module')->getPath('stanford_person') .
    "/lib/assets/img/stanford-person-default-profile-image.png"
  );
  $file_system->prepareDirectory($destination, FileSystemInterface::CREATE_DIRECTORY);
  $saved = $file_system->copy($source, $destination, FileExists::Replace);

  return $saved;
}
