<?php

/**
 * @file
 * stanford_profile_helper_helper.module
 */

use Drupal\Core\Hook\Attribute\LegacyModuleImplementsAlter;
use Drupal\Core\Site\Settings;

/**
 * Implements hook_module_implements_alter().
 *
 * This must remain a procedural implementation since it operates on the
 * list of hook implementations before they are dispatched.
 */
#[LegacyModuleImplementsAlter]
function stanford_profile_helper_module_implements_alter(&$implementations, $hook) {
  // Only for test scenarios, disable all hooks in the next module since they
  // cause errors with the containers in unit tests. It's just easier to remove
  // the hooks than to work around the errors.
  if (Settings::get('STANFORD_PROFILE_HELPER_DISABLE_NEXT')) {
    unset($implementations['next']);
  }
  if ($hook === 'plugin_filter_block__layout_builder_alter') {
    unset($implementations['menu_block']);
  }
}
