<?php

/**
 * @file
 * stanford_profile_helper.install
 */

/**
 * Implements hook_update_last_removed().
 */
function stanford_profile_helper_update_last_removed() {
  return 8195;
}

/**
 * Install new submodule.
 */
function stanford_profile_helper_update_8196() {
  \Drupal::service('module_installer')->install(['stanford_decoupled']);
}

/**
 * Convert pdb react blocks in layout builder to pdb_component.
 */
function stanford_profile_helper_update_8197() {
  $node_storage = \Drupal::entityTypeManager()->getStorage('node');
  $nids = $node_storage->getQuery()
    ->accessCheck(FALSE)
    ->condition('layout_builder__layout', '%react_component:%', 'LIKE')
    ->execute();
  foreach ($node_storage->loadMultiple($nids) as $node) {
    /** @var \Drupal\layout_builder\Field\LayoutSectionItemList $layout */
    $layout = $node->get('layout_builder__layout');

    foreach ($layout->getSections() as $section) {
      foreach ($section->getComponents() as $component) {
        if (str_starts_with($component->getPluginId(), 'react_component:')) {
          $config = $component->get('configuration');
          $config['id'] = str_replace('react_component:', 'pdb_component:', $config['id']);
          $config['provider'] = 'stanford_profile_helper';
          $component->setConfiguration($config);
        }
      }
    }
    $node->save();
  }
}
