<?php

/**
 * @file
 * File description.
 *
 * Long description.
 */

use Drupal\Core\Template\Attribute;

/**
 * Implements hook_page_attachments().
 */
function jumpstart_ui_page_attachments(array &$page) {
  // It is recommended that you don't just add a library to all pages but
  // rather, conditionally require this library only where it is needed.
  // See: https://www.drupal.org/node/2274843
  // Only add on non-admin pages.
  if (\Drupal::service('router.admin_context')->isAdminRoute() == FALSE) {
    $page['#attached']['library'][] = 'jumpstart_ui/base';
    $page['#attached']['library'][] = 'jumpstart_ui/layout';
    $page['#attached']['library'][] = 'jumpstart_ui/jumpstart_ui';
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function jumpstart_ui_preprocess_field__su_stat_button(&$variables) {
  $entity = $variables['element']['#object'];
  if ($entity->get('su_stat_link_style')?->getString() == 'action') {
    $variables['items'][0]['content']['#options']['attributes']['class'] = ['su-link--action'];
  }
}

/**
 * Implements hook_field_widget_complete_WIDGET_TYPE_form_alter().
 */
function jumpstart_ui_field_widget_complete_color_field_widget_box_form_alter(&$field_widget_complete_form, \Drupal\Core\Form\FormStateInterface $form_state, $context) {
  /** @var \Drupal\Core\Field\FieldItemListInterface $items */
  $items = $context['items'];
  if (in_array($items->getFieldDefinition()->getName(), [
    'su_stat_icon_color',
    'su_stat_stat_color',
  ])) {
    $field_widget_complete_form['#states'] = [
      'invisible' => [
        'input[name="su_stat_bg_color[0][color]"]' => ['filled' => TRUE],
      ],
    ];
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function jumpstart_ui_preprocess_layout(&$variables) {
  $current_route = \Drupal::routeMatch()->getRouteName();
  if (str_starts_with($current_route, 'layout_builder.')) {
    // Add a flag if the user is currently in layout builder. This allows the
    // template to make it easier for users to move blocks in layout builder.
    $variables['layout_builder_admin'] = TRUE;
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function jumpstart_ui_preprocess_media(&$variables) {
  $variables['attributes']['class'][] = 'media-entity-wrapper';
  $variables['attributes']['class'][] = $variables['elements']['#media']->bundle();
}
