<?php

/**
 * @file
 * File description.
 *
 * Long description.
 */

use Drupal\Component\Utility\Html;
use Drupal\Core\Template\Attribute;
use Drupal\Core\Url;
use Drupal\paragraphs\ParagraphInterface;
use Drupal\ui_patterns\Element\PatternContext;
use Drupal\ui_patterns\UiPatterns;
use Symfony\Component\HttpKernel\Exception\HttpExceptionInterface;

/**
 * Implements hook_page_attachments().
 */
function jumpstart_ui_page_attachments(array &$page) {
  // It is recommended that you don't just add a library to all pages but
  // rather, conditionally require this library only where it is needed.
  // See: https://www.drupal.org/node/2274843
  // Only add on non-admin pages.
  if (\Drupal::service('router.admin_context')->isAdminRoute() == FALSE) {
    $page['#attached']['library'][] = 'jumpstart_ui/base';
    $page['#attached']['library'][] = 'jumpstart_ui/layout';
    $page['#attached']['library'][] = 'jumpstart_ui/jumpstart_ui';
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function jumpstart_ui_preprocess_field__su_stat_button(&$variables) {
  $entity = $variables['element']['#object'];
  if ($entity->get('su_stat_link_style')?->getString() == 'action') {
    $variables['items'][0]['content']['#options']['attributes']['class'] = ['su-link--action'];
  }
}

/**
 * Implements hook_field_widget_complete_WIDGET_TYPE_form_alter().
 */
function jumpstart_ui_field_widget_complete_color_field_widget_box_form_alter(&$field_widget_complete_form, \Drupal\Core\Form\FormStateInterface $form_state, $context) {
  /** @var \Drupal\Core\Field\FieldItemListInterface $items */
  $items = $context['items'];
  if (in_array($items->getFieldDefinition()->getName(), [
    'su_stat_icon_color',
    'su_stat_stat_color',
  ])) {
    $field_widget_complete_form['#states'] = [
      'invisible' => [
        'input[name="su_stat_bg_color[0][color]"]' => ['filled' => TRUE],
      ],
    ];
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function jumpstart_ui_preprocess_ds_entity_view(&$variables) {
  /** @var \Drupal\Core\Entity\FieldableEntityInterface $entity */
  $entity = $variables['content']['#entity'];

  if ($entity->bundle() == 'stanford_stat_card') {
    if (!!$entity->get('su_stat_centered')?->getString()) {
      $variables['attributes']['class'][] = 'stat-centered';
    }

    if ($bg_color = $entity->get('su_stat_bg_color')?->getString()) {
      $variables['attributes']['class'][] = "stat-bg-$bg_color";

      // If the background color isn't a very light version, don't change the
      // icon or stat colors.
      if (!in_array($bg_color, ['f4f4f4'])) {
        return;
      }
    }

    if ($icon_color = $entity->get('su_stat_icon_color')?->getString()) {
      $variables['attributes']['class'][] = "stat-icon-$icon_color";
    }

    if ($stat_color = $entity->get('su_stat_stat_color')?->getString()) {
      $variables['attributes']['class'][] = "stat-stat-$stat_color";
    }
  }

  if (isset($variables['content']['#type']) && $variables['content']['#type'] == 'pattern') {
    $link_field = NULL;
    $link_attributes_key = NULL;
    switch ($variables['content']['#id']) {
      case 'hero':

        if (isset($variables['content']['#ds_configuration']['regions']['hero_button_link'])) {
          $link_field = reset($variables['content']['#ds_configuration']['regions']['hero_button_link']);
          $link_attributes_key = 'hero_cta_attributes';
        }
        break;

      case 'card':
        if (isset($variables['content']['#ds_configuration']['regions']['card_link'])) {
          $link_field = reset($variables['content']['#ds_configuration']['regions']['card_link']);
          $link_attributes_key = 'card_cta_attributes';
        }
        break;
    }

    if (
      $link_field &&
      $entity->hasField($link_field) &&
      $entity->get($link_field)->count()
    ) {
      $link = $entity->get($link_field);
      $options = $link->get(0)->get('options')->getValue();
      $variables['content']['#fields'][$link_attributes_key] = new Attribute($options['attributes'] ?? []);
    }
  }
}

/**
 * Implements hook_preprocess().
 */
function jumpstart_ui_preprocess(&$variables, $hook) {
  // Only want pattern contexts.
  if (!(isset($variables['context']) && $variables['context'] instanceof PatternContext)) {
    return;
  }

  // Match the hook with a strpos because it is not consistent.
  foreach (UiPatterns::getPatternDefinitions() as $pattern_id => $pattern) {
    if (str_contains($hook, $pattern_id)) {
      if (isset($variables['attributes']['id'])) {
        $variables['attributes']['id'] = Html::getUniqueId($variables['attributes']['id']);
      }

      $definition = $pattern->toArray();
      if (isset($variables['variant']) && isset($definition['variants'][$variables['variant']]['modifier_class'])) {
        $variables['modifier_class'] = $definition['variants'][$variables['variant']]['modifier_class'];
      }
      break;
    }
  }
}

/**
 * Implements hook_preprocess_patterns_overview_page().
 */
function jumpstart_ui_preprocess_patterns_overview_page(&$variables) {
  uasort($variables['patterns'], fn($pattern_a, $pattern_b) => strcmp($pattern_a['label'], $pattern_b['label']));
}

/**
 * Implements hook_preprocess_HOOK().
 */
function jumpstart_ui_preprocess_pattern_localfooter(&$variables) {
  $variables['#cache']['tags'][] = 'config_pages:stanford_local_footer';

  if (
    !empty($variables['weblogin_text']) &&
    \Drupal::currentUser()->isAnonymous()
  ) {
    $variables['#cache']['contexts'][] = 'url.path';

    $module_handler = \Drupal::moduleHandler();
    $current_request = \Drupal::requestStack()->getCurrentRequest();
    $exception = $current_request->attributes->get('exception');
    $destination = $current_request?->getPathInfo() ?: '/';
    // If the page is not a 200 response, set the destination as the home page.
    // This will be applicable for 404 and 403 pages.
    if ($exception instanceof HttpExceptionInterface && $exception->getStatusCode() != 200) {
      $destination = '/';
    }

    $options = ['query' => ['destination' => $destination]];

    if ($module_handler->moduleExists('simplesamlphp_auth')) {
      $route = Url::fromRoute('simplesamlphp_auth.saml_login', [], $options);
      $variables['#cache']['contexts'][] = 'url.path';
    }
    elseif ($module_handler->moduleExists('samlauth')) {
      $route = Url::fromRoute('samlauth.saml_controller_login', [], $options);
      $variables['#cache']['contexts'][] = 'url.path';
    }
    else {
      $route = Url::fromRoute('user.login');
    }
    $variables['weblogin_url'] = $route->toString(TRUE)->getGeneratedUrl();
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function jumpstart_ui_preprocess_layout(&$variables) {
  $current_route = \Drupal::routeMatch()->getRouteName();
  if (str_starts_with($current_route, 'layout_builder.')) {
    // Add a flag if the user is currently in layout builder. This allows the
    // template to make it easier for users to move blocks in layout builder.
    $variables['layout_builder_admin'] = TRUE;
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function jumpstart_ui_preprocess_media(&$variables) {
  $variables['attributes']['class'][] = 'media-entity-wrapper';
  $variables['attributes']['class'][] = $variables['elements']['#media']->bundle();
}

/**
 * Implements hook_preprocess_HOOK().
 */
function jumpstart_ui_preprocess_pattern_hero(&$variables) {
  /** @var \Drupal\ui_patterns\Element\PatternContext $context */
  $context = $variables['context'];
  $entity = $context->getProperty('entity');
  if ($entity instanceof ParagraphInterface && $entity->bundle() == 'stanford_banner') {
    $headline_attributes = new Attribute();

    $header_behavior = $entity->getBehaviorSetting('hero_pattern', 'heading', 'h2');
    preg_match('/^(\w+)(.*)$/', $header_behavior, $header_tag);
    $variables['card_headline_tag'] = $header_tag[1];

    if ($header_tag[2]) {
      $headline_attributes->addClass(trim(str_replace('.', ' ', $header_tag[2])));
    }

    if ($entity->getBehaviorSetting('hero_pattern', 'hide_heading', FALSE)) {
      $headline_attributes->addClass('visually-hidden');
    }

    $variables['card_headline_attributes'] = $headline_attributes;
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function jumpstart_ui_preprocess_paragraph__stanford_entity(&$variables) {
  /** @var \Drupal\paragraphs\ParagraphInterface $paragraph */
  $paragraph = $variables['paragraph'];

  // Pass the spotlight image size setting to the template if it exists.
  if (isset($variables['content']['#spotlight_image_size'])) {
    $variables['spotlight_image_size'] = $variables['content']['#spotlight_image_size'];
  }
}
