stanford_decoupled.settings:
  type: config_object
  mapping:
    referenced_invalidated_types:
      type: sequence
      label: Entity Types to track for decoupled invalidations
      sequence:
        type: string
        label: Entity Type ID

next.preview_url_generator.configuration.simple_preview:
  type: mapping
  mapping:
    vercel_bypass:
      type: string
      label: 'Vercel Deployment Protection bypass'
