<?php

/**
 * @file
 * Contains stanford_profile_admin.module.
 */

use \Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_link_alter().
 */
function stanford_profile_admin_link_alter(&$variables) {
  if (
    $variables['url']->isRouted() &&
    ($variables['url']->getRouteName() == 'entity.user.collection' || $variables['url']->getRouteName() == 'user.admin_index')
  ) {
    $variables['text'] = 'Users';
  }
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function stanford_profile_admin_form_menu_link_content_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['#attached']['library'][] = 'stanford_profile_admin/menu_link_form';
}
