<?php

/**
 * @file
 * stanford_policy.install
 */

/**
 * Install new policy content type.
 */
function stanford_policy_update_8001() {
  $old_logs = \Drupal::entityTypeManager()->getStorage('log')->loadMultiple();
  foreach ($old_logs as $log) {
    $log->delete();
  }
  $log_type = \Drupal::entityTypeManager()->getDefinition('su_policy_log');
  \Drupal::entityDefinitionUpdateManager()
    ->installEntityType($log_type);
}
