<?php

/**
 * @file
 * File description.
 *
 * Long description.
 */

use Drupal\Core\Entity\ContentEntityInterface;

/**
 * Callback for views ds group title formatter.
 *
 * @param string $raw
 *   The raw string from a views grouping column.
 * @param Drupal\Core\Entity\ContentEntityInterface $entity
 *   The loaded entity being rendered.
 *
 * @return string|null
 *   The date formatted with stanford_long_day_date_year
 */
function stanford_events_schedule_format_date($raw, ContentEntityInterface $entity) {
  if (!is_numeric($raw) || empty($entity->get('su_schedule_date_time')->getValue())) {
    return NULL;
  }

  // We are going to use the passed object to determine if we are looking
  // at an event that spans multiple days.
  $schedule_date_time = $entity->get('su_schedule_date_time')->getValue();
  $start_date_day = date('m-d-y', $schedule_date_time[0]['value']);
  $end_date_day = date('m-d-y', $schedule_date_time[0]['end_value']);
  $same_days = $start_date_day == $end_date_day;

  $timestring = \Drupal::service('date.formatter')->format($schedule_date_time[0]['value'], 'stanford_long_day_date_year');
  if (!$same_days) {
    $timestring .= ' - ' . \Drupal::service('date.formatter')->format($schedule_date_time[0]['end_value'], 'stanford_long_day_date_year');
  }

  return $timestring;
}
