<?php

/**
 * @file
 * stanford_events_importer.install
 */

use Drupal\migrate\Event\MigrateEvents;
use Drupal\migrate\Event\MigrateImportEvent;
use Drupal\migrate\MigrateMessage;

/**
 * Update importer for events-legacy domain.
 */
function stanford_events_importer_update_8001() {
  $config_page = \Drupal::entityTypeManager()
    ->getStorage('config_pages')
    ->load('stanford_events_importer');
  if ($config_page) {
    $url = $config_page->get('su_event_xml_url')->getString();
    $config_page->set('su_event_xml_url', str_replace('events.stanford.edu', 'events-legacy.stanford.edu', $url));
    $config_page->save();
  }

  $migration_config = \Drupal::configFactory()
    ->getEditable('migrate_plus.migration.stanford_events_importer');
  $source = $migration_config->get('process.su_event_source/uri');
  $source = [
    'plugin' => 'str_replace',
    'source' => $source,
    'search' => 'events.stanford.edu',
    'replace' => 'events-legacy.stanford.edu',
  ];
  $migration_config->set('process.su_event_source/uri', $source)->save();
}

/**
 * Update event node urls to point at the events-legacy domain.
 */
function stanford_events_importer_update_8002(&$sandbox) {
  $node_storage = \Drupal::entityTypeManager()->getStorage('node');
  if (empty($sandbox['ids'])) {
    $sandbox['ids'] = $node_storage->getQuery()
      ->accessCheck(FALSE)
      ->condition('type', 'stanford_event')
      ->condition('su_event_source', '%events.stanford.edu%', 'LIKE')
      ->execute();
    $sandbox['total'] = count($sandbox['ids']);
  }
  $node_ids = array_splice($sandbox['ids'], 0, 10);

  /** @var \Drupal\node\NodeInterface $node */
  foreach ($node_storage->loadMultiple($node_ids) as $node) {
    /** @var \Drupal\Core\Field\FieldItemInterface $field_item */
    foreach ($node->get('su_event_source') as $field_item) {
      $uri = $field_item->get('uri');
      $uri->setValue(str_replace('events.stanford.edu', 'events-legacy.stanford.edu', $uri->getString()));
    }
    $node->save();
  }

  $sandbox['#finished'] = count($sandbox['ids']) ? 1 - count($sandbox['ids']) / $sandbox['total'] : 1;
}

/**
 * Queue old events for deletion.
 */
function stanford_events_importer_update_8003() {
  $config = \Drupal::configFactory()
    ->getEditable('migrate_plus.migration.stanford_localist_importer');
  $config->set('status', TRUE)->save();

  $pluginManager = \Drupal::service('plugin.manager.migration');
  $pluginManager->clearCachedDefinitions();

  $migration = $pluginManager->createInstance('stanford_localist_importer');

  /** @var \Drupal\migrate\Plugin\migrate\id_map\Sql $id_map */
  $id_map = $migration->getIdMap();
  if (!\Drupal::database()->schema()->tableExists($id_map->mapTableName())) {
    return;
  }

  $message = new MigrateMessage();

  $event = new MigrateImportEvent($migration, $message);
  $event_dispatcher = \Drupal::service('event_dispatcher');
  $event_dispatcher->dispatch($event, MigrateEvents::POST_IMPORT);
}

/**
 * Clear Cron queue and restore deleted events.
 */
function stanford_events_importer_update_8004() {
  \Drupal::queue('localist_event_checker')->deleteQueue();

  $nids = \Drupal::database()
    ->select('migrate_map_stanford_localist_importer', 'm')
    ->fields('m', ['destid1', 'destid1'])
    ->execute()
    ->fetchAllKeyed();

  $vids = \Drupal::database()
    ->select('node_field_revision', 'n')
    ->fields('n', ['vid', 'vid'])
    ->condition('nid', $nids, 'IN')
    ->condition('uid', 0)
    ->condition('deleted', 0, '>')
    ->execute()
    ->fetchAllKeyed();

  \Drupal::database()
    ->update('node_field_data')
    ->fields(['deleted' => NULL])
    ->condition('vid', $vids, 'IN')
    ->execute();

  \Drupal::database()
    ->update('node_field_revision')
    ->fields(['deleted' => NULL])
    ->condition('vid', $vids, 'IN')
    ->execute();

  \Drupal::database()
    ->update('migrate_map_stanford_localist_importer')
    ->fields(['source_row_status' => 1])
    ->execute();
}
