<?php

/**
 * @file
 * File description.
 *
 * Long description.
 */

use Drupal\Core\Cache\CacheBackendInterface;
use Drupal\stanford_events_importer\StanfordEventsImporter;

/**
 * Fetch and save to state the org & category data.
 */
function stanford_events_importer_update_opts() {

  $client = \Drupal::httpClient();
  $importer = new StanfordEventsImporter($client);

  // Categories.
  // --------------------------------------------------------------------------.
  $cat_xml_raw = $importer->fetchXML('category-list');

  $args = [
    'guids' => '/CategoryList/Category/guid',
    'label' => '/CategoryList/Category/name',
  ];

  // Get the formatted key->value pairs.
  $key_val = $importer->parseXML($cat_xml_raw, $args);

  // Set the state storage for this site.
  \Drupal::cache()
    ->set(StanfordEventsImporter::CACHE_KEY_CAT, $key_val, CacheBackendInterface::CACHE_PERMANENT, ['stanford_events_importer']);

  // Organizations.
  // --------------------------------------------------------------------------.
  $org_xml_raw = $importer->fetchXML('organization-list');

  $args = [
    'guids' => '/OrganizationList/Organization/guid',
    'label' => '/OrganizationList/Organization/name',
  ];

  // Get the formatted key->value pairs.
  $key_val = $importer->parseXML($org_xml_raw, $args);

  // Set the state storage for this site.
  \Drupal::cache()
    ->set(StanfordEventsImporter::CACHE_KEY_ORG, $key_val, CacheBackendInterface::CACHE_PERMANENT, ['stanford_events_importer']);

  // Done.
  \Drupal::messenger()
    ->addStatus('Updated category and organization information.');
}
