<?php

/**
 * @file
 * Primary module hooks for stanford_layout_paragraphs module.
 */

use Drupal\Core\Template\Attribute;
use Drupal\views\ViewExecutable;
use Drupal\Component\Utility\Html;

/**
 * Implements hook_library_info_alter().
 */
function stanford_layout_paragraphs_library_info_alter(&$libraries, $extension) {
  if ($extension == 'layout_paragraphs') {
    $libraries['builder']['dependencies'][] = 'stanford_layout_paragraphs/layout_paragraphs';
  }
}

/**
 * Implements hook_preprocess().
 */
function stanford_layout_paragraphs_preprocess(&$variables, $hook) {
  // If not editing LP page, we don't want to do anything.
  if (!_stanford_layout_paragraphs_is_editing_layout_paragraphs()) {
    return;
  }

  // Remove any contextual links on the media/paragraphs/other entities when
  // editing the layout paragraphs page.
  if (!empty($variables['elements']['#entity_type'])) {
    unset($variables['title_suffix']['contextual_links']);
  }
}

/**
 * Is the user currently on editing the layout paragraphs?
 *
 * @return bool
 *   True if the route matches known routes for LP.
 */
function _stanford_layout_paragraphs_is_editing_layout_paragraphs() {
  $layout_paragraphs_routes = ['entity.node.edit_form'];
  $route_name = \Drupal::routeMatch()->getRouteName();
  return $route_name && (in_array($route_name, $layout_paragraphs_routes) || str_starts_with($route_name, 'layout_paragraphs.'));
}

/**
 * Implements hook_paragraphs_behavior_info_alter().
 */
function stanford_layout_paragraphs_paragraphs_behavior_info_alter(&$paragraphs_behavior) {
  $paragraphs_behavior['layout_paragraphs']['class'] = 'Drupal\stanford_layout_paragraphs\Plugin\paragraphs\Behavior\LayoutParagraphs';
}

/**
 * Implements hook_views_pre_execute().
 */
function stanford_layout_paragraphs_views_pre_execute(ViewExecutable $view) {
  $excluded_views = ['media_library'];
  if (
    _stanford_layout_paragraphs_is_editing_layout_paragraphs() &&
    !in_array($view->id(), $excluded_views)
  ) {
    $current_limit = $view->query->getLimit();
    if ($current_limit <= 0 || $current_limit > 5) {
      $view->query->setLimit(6);
    }
  }
}
