<?php

/**
 * @file
 * Contains stanford_person_importer.module.
 */

use Drupal\Core\Cache\Cache;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\config_pages\ConfigPagesInterface;
use Drupal\node\NodeInterface;

/**
 * Implements hook_help().
 */
function stanford_person_importer_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the stanford_person_importer module.
    case 'help.page.stanford_person_importer':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Migration support for importing of profile information from stanford.edu.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_field_widget_form_alter().
 */
function stanford_person_importer_field_widget_form_alter(&$element, FormStateInterface $form_state, $context) {
  $field_name = $context['items']->getFieldDefinition()->getName();
  if ($field_name == 'su_person_cap_password') {
    // Validate the credentials on the config pages entity form.
    $element['#element_validate'][] = [
      'Drupal\stanford_person_importer\Cap',
      'validateCredentials',
    ];
  }
}

/**
 * Implements hook_ENTITY_TYPE_presave().
 *
 * Before saving imported nodes, set the photo field to a default value if it
 * doesn't have any legitimate media items.
 */
function stanford_person_importer_node_presave(NodeInterface $entity) {
  /** @var \Drupal\stanford_migrate\StanfordMigrateInterface $stanford_migrate */
  $stanford_migrate = \Drupal::service('stanford_migrate');
  // Don't worry about nodes that were manually created or if the field is gone.
  if (!$entity->hasField('su_person_photo') || !$stanford_migrate->getNodesMigration($entity)) {
    return;
  }
  $photo_values = $entity->get('su_person_photo')->getValue();
  $media_storage = \Drupal::entityTypeManager()->getStorage('media');
  foreach ($photo_values as $value) {
    // If any delta value has a valid media entity, we don't need to set the
    // default field value.
    if ($media_storage->load($value['target_id'])) {
      return;
    }
  }

  $default_photo = $entity->getFieldDefinition('su_person_photo')
    ->getDefaultValue($entity);
  // Set the default value of the photo field.
  $entity->set('su_person_photo', $default_photo);
}

/**
 * Implements hook_ENTITY_TYPE_presave().
 */
function stanford_person_importer_config_pages_presave(ConfigPagesInterface $entity) {
  if ($entity->bundle() == 'stanford_person_importer') {
    $terms = \Drupal::entityTypeManager()
      ->getStorage('taxonomy_term')
      ->getQuery()
      ->accessCheck(FALSE)
      ->condition('vid', 'cap_org_codes')
      ->execute();

    // No org codes exist, lets load them up.
    if (empty($terms)) {
      \Drupal::service('stanford_person_importer.cap')
        ->setClientId($entity->get('su_person_cap_username')->getString())
        ->setClientSecret($entity->get('su_person_cap_password')->getString())
        ->updateOrganizations();
    }

    // Invalidate the migration cache since some of the org codes or workgroups
    // probably changed.
    Cache::invalidateTags(['migration_plugins']);
  }
}
